branch-defaults:
  default:
    environment: env-flutter
    group_suffix: null
global:
  application_name: django-flutter
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
