# Generated by Django 2.1.1 on 2020-04-29 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Reg_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('User_Name', models.CharField(max_length=100)),
                ('User_Phone', models.CharField(max_length=100)),
                ('User_Email', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='VendorsCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorCategory_ID', models.CharField(max_length=50)),
                ('VendorCategory_Name', models.CharField(max_length=100)),
                ('VendorCategory_Image', models.ImageField(upload_to='vendorcategoryimages/')),
            ],
            options={
                'db_table': 'VendorsCategoryData',
            },
        ),
        migrations.CreateModel(
            name='VendorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Reg_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Vendor_ID', models.CharField(max_length=50)),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Vendor_Category', models.CharField(max_length=100)),
                ('Vendor_Owner', models.CharField(max_length=100)),
                ('Vendor_Address', models.CharField(max_length=1000)),
                ('Vendor_City', models.CharField(max_length=100)),
                ('Vendor_State', models.CharField(max_length=100)),
                ('Vendor_Phone', models.CharField(max_length=100)),
                ('Vendor_Email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'VendorsData',
            },
        ),
    ]
