# Generated by Django 2.1.1 on 2020-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200429_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='User_Name',
            new_name='User_First_Name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='User_Last_Name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
