# Generated by Django 2.1.1 on 2020-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200429_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorscategorydata',
            name='VendorCategory_ID',
        ),
        migrations.RemoveField(
            model_name='vendorscategorydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vendorsdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='vendorscategorydata',
            name='VendorCategory_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendorsdata',
            name='Vendor_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
